/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Language {
  code: string;
  name: string;
  nativeName: string;
}

export const LANGUAGES: Language[] = [
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "pt-ao", name: "Angolan Portuguese", nativeName: "Português (Angola)" },
  { code: "en", name: "English", nativeName: "English" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "zh", name: "Chinese Simplified", nativeName: "简体中文" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "ro", name: "Romanian", nativeName: "Română" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { code: "he", name: "Hebrew", nativeName: "עברית" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "tl", name: "Tagalog", nativeName: "Filipino" },
  { code: "fa", name: "Persian", nativeName: "فارسی" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "xh", name: "Xhosa", nativeName: "isiXhosa" },
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina" },
  { code: "bg", name: "Bulgarian", nativeName: "Български" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski" },
  { code: "sr", name: "Serbian", nativeName: "Српски" },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu" },
  { code: "et", name: "Estonian", nativeName: "Eesti" }
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  pt: {
    loginTitle: "Login do Investidor",
    registerTitle: "Criar Conta de Investidor",
    emailPlaceholder: "Introduza o seu email",
    passwordPlaceholder: "Introduza a sua senha (mín. 6 caracteres)",
    fullNamePlaceholder: "Nome completo (apelido)",
    phonePlaceholder: "Número de telefone",
    inviteCodePlaceholder: "ID de convite (opcional)",
    loginBtn: "Entrar",
    registerBtn: "Criar Conta",
    noAccount: "Não tem uma conta?",
    hasAccount: "Já tem uma conta?",
    errorCreatingAccount: "Erro ao criar conta? Contacte o Telegram",
    errorLogin: "Credenciais incorretas ou falha no servidor.",
    balanceLabel: "Saldo Disponível",
    earnings60Days: "Rendimento projetado para 60 dias:",
    acquireBtn: "Adquira Já",
    confirmTitle: "Confirmar Aquisição",
    confirmQuestion: "Deseja adquirir o plano por",
    insufficientBalance: "Saldo insuficiente. Por favor, financie a sua conta.",
    pinPrompt: "Introduza o seu PIN de transação de 4 dígitos",
    pinIncorrect: "PIN de transação incorreto.",
    acquiredSuccess: "Plano adquirido com sucesso!",
    loading: "A processar...",
    withdrawalTitle: "Efetuar Levantamento",
    withdrawalMinError: "O limite mínimo de levantamento é 603,73 kz",
    withdrawalLimitWeekend: "Aos sábados e domingos levantamentos apenas das 12h30 às 13h30.",
    withdrawalSuccess: "Levantamento solicitado com sucesso!",
    copiedReferral: "Link de convite copiado!",
    myCommunity: "Minha Comunidade",
    transactionsTab: "Transações",
    logoutBtn: "Terminar Sessão",
    aboutHeading: "A Anglo American é uma multinacional líder em prospecção sustentável.",
    welcomeBack: "Bem-vindo de volta!",
    welcomeText: "Pronto para gerir a sua carteira de transição energética?",
    claimBonusBtn: "Reclamar Bónus de Boas-Vindas de 200,92 kz",
    bonusClaimedSuccess: "Bónus de 200,92 kz creditado com sucesso!",
    referredCount: "Amigos convidados:",
    commissionEarned: "Ganhos em comissão (10%):",
    bankDetailsTitle: "Coordenadas Bancárias para Levantamento",
    bankSaveWarning: "Atenção: Ao guardar as suas coordenadas bancárias, estas não poderão ser editadas ou eliminadas e serão mascaradas por motivos de segurança.",
    saveBtn: "Guardas Coordenadas",
    bankMasqued: "Dados Bancários Ativos",
    operationsTitle: "Centro de Operações (Colheita Diária)",
    noActiveInvestments: "Não possui investimentos ativos no momento. Vá a Pacotes de Aquisição para começar.",
    collectYieldBtn: "Recolher Rendimento Diário",
    yieldSuccess: "Rendimento diário recolhido com sucesso!",
    financingTitle: "Financiamento de Conta",
    selectCountry: "Selecione o seu país de residência",
    customSupportBtn: "Apoio Personalizado no Telegram",
    proofPlaceholder: "Cole o ID ou URL do comprovativo de depósito",
    submitProofBtn: "Enviar Comprovativo para Aprovação",
    proofSubmittedSuccess: "Comprovativo enviado! Aguarde validação pelo operador.",
    dashboardMenu: "Anglo American",
    securityPrivacy: "Segurança e Privacidade",
    updatePasswords: "Atualizar Senhas de Acesso e Transação",
    newLoginPassword: "Nova Senha de Acesso (Login)",
    newTransactionPin: "Novo PIN de Transação (4 dígitos)",
    saveSecurityChanges: "Gravar Alterações de Segurança",
    secSuccess: "Configurações de segurança atualizadas!"
  },
  "pt-ao": {
    loginTitle: "Login do Investidor",
    registerTitle: "Criar Conta de Investidor",
    emailPlaceholder: "Introduza o seu email",
    passwordPlaceholder: "Introduza a sua senha (mín. 6 caracteres)",
    fullNamePlaceholder: "Nome completo (apelido)",
    phonePlaceholder: "Número de telefone",
    inviteCodePlaceholder: "ID de convite (opcional)",
    loginBtn: "Entrar",
    registerBtn: "Criar Conta",
    noAccount: "Não tem uma conta?",
    hasAccount: "Já tem uma conta?",
    errorCreatingAccount: "Erro ao criar conta? Contacte o Telegram",
    errorLogin: "Credenciais incorretas ou falha no servidor.",
    balanceLabel: "Saldo Disponível",
    earnings60Days: "Rendimento projetado para 60 dias:",
    acquireBtn: "Adquira Já",
    confirmTitle: "Confirmar Aquisição",
    confirmQuestion: "Deseja adquirir o plano por",
    insufficientBalance: "Saldo insuficiente. Por favor, financie a sua conta.",
    pinPrompt: "Introduza o seu PIN de transação de 4 dígitos",
    pinIncorrect: "PIN de transação incorreto.",
    acquiredSuccess: "Plano adquirido com sucesso!",
    loading: "A processar...",
    withdrawalTitle: "Efetuar Levantamento",
    withdrawalMinError: "O limite mínimo de levantamento é 603,73 kz",
    withdrawalLimitWeekend: "Aos sábados e domingos levantamentos apenas das 12h30 às 13h30.",
    withdrawalSuccess: "Levantamento solicitado com sucesso!",
    copiedReferral: "Link de convite copiado!",
    myCommunity: "Minha Comunidade",
    transactionsTab: "Transações",
    logoutBtn: "Terminar Sessão",
    aboutHeading: "A Anglo American é uma multinacional líder em prospecção sustentável.",
    welcomeBack: "Bem-vindo de volta!",
    welcomeText: "Pronto para gerir a sua carteira de transição energética?",
    claimBonusBtn: "Reclamar Bónus de Boas-Vindas de 200,92 kz",
    bonusClaimedSuccess: "Bónus de 200,92 kz creditado com sucesso!",
    referredCount: "Amigos convidados:",
    commissionEarned: "Ganhos em comissão (10%):",
    bankDetailsTitle: "Coordenadas Bancárias para Levantamento",
    bankSaveWarning: "Atenção: Ao guardar as suas coordenadas bancárias, estas não poderão ser editadas ou eliminadas e serão mascaradas por motivos de segurança.",
    saveBtn: "Guardas Coordenadas",
    bankMasqued: "Dados Bancários Ativos",
    operationsTitle: "Centro de Operações (Colheita Diária)",
    noActiveInvestments: "Não possui investimentos ativos no momento. Vá a Pacotes de Aquisição para começar.",
    collectYieldBtn: "Recolher Rendimento Diário",
    yieldSuccess: "Rendimento diário recolhido com sucesso!",
    financingTitle: "Financiamento de Conta",
    selectCountry: "Selecione o seu país de residência",
    customSupportBtn: "Apoio Personalizado no Telegram",
    proofPlaceholder: "Cole o ID ou URL do comprovativo de depósito",
    submitProofBtn: "Enviar Comprovativo para Aprovação",
    proofSubmittedSuccess: "Comprovativo enviado! Aguarde validação pelo operador.",
    dashboardMenu: "Anglo American",
    securityPrivacy: "Segurança e Privacidade",
    updatePasswords: "Atualizar Senhas de Acesso e Transação",
    newLoginPassword: "Nova Senha de Acesso (Login)",
    newTransactionPin: "Novo PIN de Transação (4 dígitos)",
    saveSecurityChanges: "Gravar Alterações de Segurança",
    secSuccess: "Configurações de segurança atualizadas!"
  }
};

// Fill matching phrases in other languages to support the select input dynamically
// Falling back gracefully to English phrases structured matching standard keys.
export const getTranslation = (langCode: string, key: string): string => {
  const code = TRANSLATIONS[langCode] ? langCode : "pt";
  const group = TRANSLATIONS[code];
  if (group && group[key]) {
    return group[key];
  }
  // Fallback to Portuguese
  return TRANSLATIONS["pt"][key] || key;
};
